### ISSUE TITLE
Semi-hard or hard?

### ISSUE THREAD

**Issue by BrandonHanx** [Confusezius/ECCV2020_DiVA_MultiFeature_DML#2]
https://github.com/Confusezius/ECCV2020_DiVA_MultiFeature_DML/blob/73c10e07e957457982257a097139f5811fedd087/batchminer/semihard.py#L27-L30

Hey, for the implementation of semi-hard batch miner, you directly used min and max. I guess this is a hard manner rather than semi-hard one.

Please point me out if I were wrong.

**Comment by Confusezius** [comment]
Hi! You are indeed right! There was a porting issue when forking this repo from the https://github.com/Confusezius/Revisiting_Deep_Metric_Learning_PyTorch repository - I didn't check that because it wasn't relevant for this specific paper ( we never test or make use of semihard mining if I recall correctly). If you check the source repo, you will realize that this is the batchminer dubbed "softhard.py" rather than the correct "semihard.py". I'll fix this soon!

**Comment by BrandonHanx** [comment]
Thanks for your reply. This issue is solved for me.
